# 09 — Repeated-seed and estimation-window robustness

Repeat the rolling experiment so conclusions do not depend on one random seed. The first run uses classical models and is relatively quick. A separate cell adds DI-VAR because retraining it for each seed is intentionally more expensive.

In [1]:
import sys
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path.cwd()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT / 'src'))
CACHE = ROOT / 'results/notebook_cache'
CACHE.mkdir(parents=True, exist_ok=True)
from innovcal.experiments.repeated import (
    run_repeated_rolling_experiment,
    summarize_repeated_results,
)

In [2]:
returns = pd.read_csv(ROOT / 'data/processed/financial_returns.csv', index_col=0).to_numpy()
SEEDS = (101, 202, 303)
CLASSICAL = ('gaussian', 'student_t', 'bootstrap', 'block_bootstrap', 'volatility_bootstrap')

classical_repeats = run_repeated_rolling_experiment(
    returns,
    seeds=SEEDS,
    methods=CLASSICAL,
    window_lengths=(None, 1000),
    horizon=20,
    origin_step=20,
    n_paths=250,
)
display(summarize_repeated_results(classical_repeats))

/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: divide by zero encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: overflow encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: invalid value encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: divide by zero encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: overflow encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: invalid value encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: divide by zero encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: overflow encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: invalid value encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: divide by zero encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: overflow encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: invalid value encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: divide by zero encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: overflow encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: invalid value encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: divide by zero encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: overflow encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: invalid value encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: divide by zero encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: overflow encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: invalid value encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: divide by zero encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: overflow encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: invalid value encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: divide by zero encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: overflow encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: invalid value encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: divide by zero encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: overflow encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: invalid value encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: divide by zero encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: overflow encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/gaussian.py:34: RuntimeWarning: invalid value encountered in matmul
  shocks = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: divide by zero encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: overflow encountered in matmul
  z = rng.multivariate_normal(
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/innovations/student_t.py:49: RuntimeWarning: invalid value encountered in matmul
  z = rng.multivariate_normal(

        innovation_model horizon     window avg_coverage            \
                                                    mean       std
0        block_bootstrap       1       1000     0.936170  0.005319
1        block_bootstrap       1  expanding     0.946809  0.005319
2        block_bootstrap       5       1000     0.932624  0.008125
3        block_bootstrap       5  expanding     0.930851  0.005319
4        block_bootstrap      20       1000     0.925532  0.009213
5        block_bootstrap      20  expanding     0.925532  0.010638
6              bootstrap       1       1000     0.941489  0.005319
7              bootstrap       1  expanding     0.946809  0.005319
8              bootstrap       5       1000     0.934397  0.008125
9              bootstrap       5  expanding     0.937943  0.008125
10             bootstrap      20       1000     0.934397  0.016250
11             bootstrap      20  expanding     0.937943  0.016250
12              gaussian       1       1000     0.957447  0.005319
13              gaussian       1  expanding     0.962766  0.009213
14              gaussian       5       1000     0.943262  0.003071
15              gaussian       5  expanding     0.948582  0.003071
16              gaussian      20       1000     0.950355  0.003071
17              gaussian      20  expanding     0.952128  0.005319
18             student_t       1       1000     0.948582  0.006142
19             student_t       1  expanding     0.952128  0.005319
20             student_t       5       1000     0.937943  0.003071
21             student_t       5  expanding     0.939716  0.003071
22             student_t      20       1000     0.943262  0.006142
23             student_t      20  expanding     0.945035  0.008125
24  volatility_bootstrap       1       1000     0.946809  0.005319
25  volatility_bootstrap       1  expanding     0.957447  0.005319
26  volatility_bootstrap       5       1000     0.943262  0.003071
27  volatility_bootstrap       5  expanding     0.937943  0.003071
28  volatility_bootstrap      20       1000     0.941489  0.005319
29  volatility_bootstrap      20  expanding     0.941489  0.005319

   abs_coverage_error           avg_width                 ece            \
                 mean       std      mean       std      mean       std
0            0.036170  0.005319  0.055275  0.000308  0.080496  0.003071
1            0.046809  0.005319  0.055275  0.000308  0.080496  0.003546
2            0.032624  0.008125  0.055802  0.000511  0.050355  0.001773
3            0.030851  0.005319  0.055398  0.000439  0.046809  0.001773
4            0.025532  0.009213  0.055240  0.000584  0.026714  0.008379
5            0.025532  0.010638  0.054922  0.000630  0.026123  0.001024
6            0.041489  0.005319  0.055010  0.000394  0.081087  0.006713
7            0.046809  0.005319  0.055010  0.000394  0.081087  0.002047
8            0.034397  0.008125  0.055688  0.000301  0.052128  0.003546
9            0.037943  0.008125  0.055523  0.000229  0.047991  0.002708
10           0.034397  0.016250  0.055897  0.000177  0.030851  0.010785
11           0.037943  0.016250  0.055706  0.000315  0.034397  0.014184
12           0.057447  0.005319  0.062909  0.000124  0.144326  0.006393
13           0.062766  0.009213  0.062909  0.000124  0.145508  0.002708
14           0.043262  0.003071  0.062990  0.000170  0.121868  0.006713
15           0.048582  0.003071  0.062892  0.000085  0.122459  0.009099
16           0.050355  0.003071  0.063229  0.000305  0.113593  0.001024
17           0.052128  0.005319  0.063039  0.000327  0.111229  0.002708
18           0.048582  0.006142  0.058839  0.000703  0.111820  0.002708
19           0.052128  0.005319  0.058839  0.000703  0.115957  0.003546
20           0.037943  0.003071  0.060787  0.000252  0.087589  0.006393
21           0.039716  0.003071  0.060606  0.000251  0.087589  0.007729
22           0.043262  0.006142  0.059695  0.000228  0.075177  0.003071
23           0.045035  0.008125  0.059497  0.000336  0.071631  0.005319
24           0.046809  0.005319  0.060978  0.000319  0.117730  0.004691
25           0.057447  0.005319  0.060978  0.000319  0.117139  0.007995
26           0.043262  0.003071  0.061083  0.000134  0.095272  0.005417
27           0.037943  0.003071  0.060865  0.000155  0.092317  0.002708
28           0.041489  0.005319  0.061134  0.000393  0.082270  0.007092
29           0.041489  0.005319  0.060893  0.000151  0.076950  0.010638

   pit_deviation                crps           energy_score            \
            mean       std      mean       std         mean       std
0       0.026099  0.003736  0.006907  0.000023     0.016627  0.000051
1       0.027021  0.002301  0.006941  0.000024     0.016707  0.000045
2       0.021064  0.002096  0.007711  0.000039     0.018608  0.000062
3       0.020142  0.001509  0.007716  0.000041     0.018616  0.000075
4       0.014539  0.003271  0.008141  0.000047     0.019249  0.000076
5       0.018156  0.001172  0.008138  0.000050     0.019214  0.000084
6       0.026950  0.000806  0.006961  0.000035     0.016812  0.000087
7       0.025106  0.000563  0.006992  0.000026     0.016871  0.000082
8       0.022340  0.001915  0.007693  0.000044     0.018582  0.000095
9       0.020000  0.002956  0.007706  0.000039     0.018611  0.000100
10      0.017943  0.004575  0.008201  0.000015     0.019371  0.000046
11      0.016667  0.003187  0.008183  0.000021     0.019320  0.000057
12      0.052908  0.002131  0.007373  0.000004     0.017548  0.000059
13      0.051277  0.000737  0.007386  0.000004     0.017594  0.000048
14      0.045390  0.003071  0.008026  0.000038     0.019167  0.000103
15      0.046099  0.002215  0.008029  0.000040     0.019187  0.000107
16      0.035248  0.001172  0.008485  0.000022     0.019967  0.000052
17      0.036170  0.001185  0.008473  0.000020     0.019931  0.000056
18      0.038511  0.002096  0.007111  0.000039     0.017022  0.000136
19      0.037589  0.001494  0.007131  0.000050     0.017078  0.000151
20      0.030567  0.003466  0.007852  0.000038     0.018808  0.000073
21      0.030496  0.002215  0.007858  0.000032     0.018826  0.000069
22      0.022553  0.001915  0.008292  0.000012     0.019529  0.000048
23      0.021560  0.003937  0.008275  0.000019     0.019476  0.000061
24      0.041348  0.003625  0.007175  0.000010     0.017179  0.000051
25      0.037163  0.002694  0.007201  0.000019     0.017239  0.000063
26      0.034397  0.001625  0.007818  0.000026     0.018811  0.000085
27      0.031206  0.002215  0.007818  0.000025     0.018812  0.000087
28      0.023901  0.000684  0.008300  0.000055     0.019580  0.000117
29      0.023475  0.001092  0.008278  0.000051     0.019519  0.000115

   interval_score
             mean       std
0        0.064135  0.001033
1        0.063571  0.000931
2        0.066892  0.001551
3        0.066496  0.001703
4        0.070021  0.001493
5        0.069871  0.001556
6        0.064354  0.001264
7        0.064028  0.001400
8        0.065860  0.000969
9        0.065639  0.000468
10       0.071057  0.001318
11       0.070627  0.001151
12       0.068714  0.000465
13       0.068397  0.000045
14       0.068947  0.000659
15       0.068890  0.000476
16       0.074673  0.000894
17       0.074556  0.000789
18       0.067110  0.000551
19       0.066249  0.000986
20       0.067906  0.001060
21       0.067491  0.001268
22       0.072973  0.001234
23       0.072855  0.001140
24       0.068921  0.000312
25       0.068028  0.000840
26       0.067703  0.000497
27       0.067453  0.000188
28       0.073267  0.000494
29       0.073309  0.000564

## Optional DI-VAR repeats

Run this cell for the final analysis. Validation-based early stopping selects a checkpoint separately for each seed. Start with the expanding window; add the 1000-day window only if that comparison is central to the written claim.

In [3]:
RUN_DIFFUSION_REPEATS = False
diffusion_repeats = pd.DataFrame()
if RUN_DIFFUSION_REPEATS:
    diffusion_repeats = run_repeated_rolling_experiment(
        returns,
        seeds=SEEDS,
        methods=('diffusion',),
        window_lengths=(None,),
        horizon=20,
        origin_step=20,
        n_paths=250,
        diffusion_options={
            'timesteps': 100,
            'epochs': 300,
            'hidden_dim': 128,
            'batch_size': 64,
            'validation_fraction': 0.2,
            'early_stopping_patience': 40,
            'verbose': False,
        },
    )
    display(summarize_repeated_results(diffusion_repeats))
else:
    print('Set RUN_DIFFUSION_REPEATS=True for final DI-VAR repetitions.')

Set RUN_DIFFUSION_REPEATS=True for final DI-VAR repetitions.

## Optional CDI-VAR repeats

This is the final, most expensive comparison. It repeats training, conditional recursive sampling, and explicit calibration for every seed. Start with three seeds and the expanding window so it remains directly comparable with the DI-VAR repetitions.

In [4]:
RUN_CDI_VAR_REPEATS = True
cdi_var_repeats = pd.DataFrame()
if RUN_CDI_VAR_REPEATS:
    cdi_var_repeats = run_repeated_rolling_experiment(
        returns,
        seeds=SEEDS,
        methods=('cdi_var',),
        window_lengths=(None,),
        horizon=20,
        origin_step=20,
        n_paths=250,
        cdi_var_options={
            'context_lags': 5,
            'volatility_span': 60,
            'validation_fraction': 0.15,
            'calibration_fraction': 0.15,
            'calibration_horizons': (1, 5, 20),
            'calibration_paths': 32,
            'calibration_shrinkage': 0.5,
            'calibration_bounds': (0.8, 1.25),
            'adaptive_calibration_window': 12,
            'timesteps': 50,
            'epochs': 300,
            'hidden_dim': 128,
            'time_embedding_dim': 32,
            'batch_size': 64,
            'early_stopping_patience': 40,
            'verbose': False,
        },
    )
    display(summarize_repeated_results(cdi_var_repeats))
else:
    print('Set RUN_CDI_VAR_REPEATS=True for final CDI-VAR repetitions.')

/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: divide by zero encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: overflow encountered in matmul
  fitted = X @ beta
/Users/jonathanma/Desktop/Projects/innovative-droBVAR/src/innovcal/vector_ar/fit.py:63: RuntimeWarning: invalid value encountered in matmul
  fitted = X @ beta

  innovation_model horizon     window avg_coverage            \
                                              mean       std
0          cdi_var       1  expanding     0.904255  0.005319
1          cdi_var       5  expanding     0.897163  0.003071
2          cdi_var      20  expanding     0.884752  0.020138

  abs_coverage_error           avg_width                 ece            \
                mean       std      mean       std      mean       std
0           0.004965  0.004299  0.046133  0.001013  0.049409  0.004140
1           0.002837  0.003071  0.047903  0.000931  0.030378  0.013069
2           0.015248  0.020138  0.048051  0.001589  0.030969  0.010389

  pit_deviation                crps           energy_score            \
           mean       std      mean       std         mean       std
0      0.026738  0.003071  0.007038  0.000017     0.016859  0.000059
1      0.018298  0.005544  0.007707  0.000037     0.018464  0.000145
2      0.019645  0.003158  0.008121  0.000061     0.019201  0.000125

  interval_score
            mean       std
0       0.059724  0.000811
1       0.062817  0.000436
2       0.068440  0.000545

In [5]:
repeated_results = pd.concat([classical_repeats, diffusion_repeats, cdi_var_repeats], ignore_index=True)
repeated_results.to_csv(CACHE / 'repeated_rolling_results.csv', index=False)
summary = summarize_repeated_results(repeated_results)
summary.to_csv(CACHE / 'repeated_rolling_summary.csv', index=False)
display(summary)

        innovation_model horizon     window avg_coverage            \
                                                    mean       std
0        block_bootstrap       1       1000     0.936170  0.005319
1        block_bootstrap       1  expanding     0.946809  0.005319
2        block_bootstrap       5       1000     0.932624  0.008125
3        block_bootstrap       5  expanding     0.930851  0.005319
4        block_bootstrap      20       1000     0.925532  0.009213
5        block_bootstrap      20  expanding     0.925532  0.010638
6              bootstrap       1       1000     0.941489  0.005319
7              bootstrap       1  expanding     0.946809  0.005319
8              bootstrap       5       1000     0.934397  0.008125
9              bootstrap       5  expanding     0.937943  0.008125
10             bootstrap      20       1000     0.934397  0.016250
11             bootstrap      20  expanding     0.937943  0.016250
12               cdi_var       1  expanding     0.904255  0.005319
13               cdi_var       5  expanding     0.897163  0.003071
14               cdi_var      20  expanding     0.884752  0.020138
15              gaussian       1       1000     0.957447  0.005319
16              gaussian       1  expanding     0.962766  0.009213
17              gaussian       5       1000     0.943262  0.003071
18              gaussian       5  expanding     0.948582  0.003071
19              gaussian      20       1000     0.950355  0.003071
20              gaussian      20  expanding     0.952128  0.005319
21             student_t       1       1000     0.948582  0.006142
22             student_t       1  expanding     0.952128  0.005319
23             student_t       5       1000     0.937943  0.003071
24             student_t       5  expanding     0.939716  0.003071
25             student_t      20       1000     0.943262  0.006142
26             student_t      20  expanding     0.945035  0.008125
27  volatility_bootstrap       1       1000     0.946809  0.005319
28  volatility_bootstrap       1  expanding     0.957447  0.005319
29  volatility_bootstrap       5       1000     0.943262  0.003071
30  volatility_bootstrap       5  expanding     0.937943  0.003071
31  volatility_bootstrap      20       1000     0.941489  0.005319
32  volatility_bootstrap      20  expanding     0.941489  0.005319

   abs_coverage_error           avg_width                 ece            \
                 mean       std      mean       std      mean       std
0            0.036170  0.005319  0.055275  0.000308  0.080496  0.003071
1            0.046809  0.005319  0.055275  0.000308  0.080496  0.003546
2            0.032624  0.008125  0.055802  0.000511  0.050355  0.001773
3            0.030851  0.005319  0.055398  0.000439  0.046809  0.001773
4            0.025532  0.009213  0.055240  0.000584  0.026714  0.008379
5            0.025532  0.010638  0.054922  0.000630  0.026123  0.001024
6            0.041489  0.005319  0.055010  0.000394  0.081087  0.006713
7            0.046809  0.005319  0.055010  0.000394  0.081087  0.002047
8            0.034397  0.008125  0.055688  0.000301  0.052128  0.003546
9            0.037943  0.008125  0.055523  0.000229  0.047991  0.002708
10           0.034397  0.016250  0.055897  0.000177  0.030851  0.010785
11           0.037943  0.016250  0.055706  0.000315  0.034397  0.014184
12           0.004965  0.004299  0.046133  0.001013  0.049409  0.004140
13           0.002837  0.003071  0.047903  0.000931  0.030378  0.013069
14           0.015248  0.020138  0.048051  0.001589  0.030969  0.010389
15           0.057447  0.005319  0.062909  0.000124  0.144326  0.006393
16           0.062766  0.009213  0.062909  0.000124  0.145508  0.002708
17           0.043262  0.003071  0.062990  0.000170  0.121868  0.006713
18           0.048582  0.003071  0.062892  0.000085  0.122459  0.009099
19           0.050355  0.003071  0.063229  0.000305  0.113593  0.001024
20           0.052128  0.005319  0.063039  0.000327  0.111229  0.002708
21           0.048582  0.006142  0.058839  0.000703  0.111820  0.002708
22           0.052128  0.005319  0.058839  0.000703  0.115957  0.003546
23           0.037943  0.003071  0.060787  0.000252  0.087589  0.006393
24           0.039716  0.003071  0.060606  0.000251  0.087589  0.007729
25           0.043262  0.006142  0.059695  0.000228  0.075177  0.003071
26           0.045035  0.008125  0.059497  0.000336  0.071631  0.005319
27           0.046809  0.005319  0.060978  0.000319  0.117730  0.004691
28           0.057447  0.005319  0.060978  0.000319  0.117139  0.007995
29           0.043262  0.003071  0.061083  0.000134  0.095272  0.005417
30           0.037943  0.003071  0.060865  0.000155  0.092317  0.002708
31           0.041489  0.005319  0.061134  0.000393  0.082270  0.007092
32           0.041489  0.005319  0.060893  0.000151  0.076950  0.010638

   pit_deviation                crps           energy_score            \
            mean       std      mean       std         mean       std
0       0.026099  0.003736  0.006907  0.000023     0.016627  0.000051
1       0.027021  0.002301  0.006941  0.000024     0.016707  0.000045
2       0.021064  0.002096  0.007711  0.000039     0.018608  0.000062
3       0.020142  0.001509  0.007716  0.000041     0.018616  0.000075
4       0.014539  0.003271  0.008141  0.000047     0.019249  0.000076
5       0.018156  0.001172  0.008138  0.000050     0.019214  0.000084
6       0.026950  0.000806  0.006961  0.000035     0.016812  0.000087
7       0.025106  0.000563  0.006992  0.000026     0.016871  0.000082
8       0.022340  0.001915  0.007693  0.000044     0.018582  0.000095
9       0.020000  0.002956  0.007706  0.000039     0.018611  0.000100
10      0.017943  0.004575  0.008201  0.000015     0.019371  0.000046
11      0.016667  0.003187  0.008183  0.000021     0.019320  0.000057
12      0.026738  0.003071  0.007038  0.000017     0.016859  0.000059
13      0.018298  0.005544  0.007707  0.000037     0.018464  0.000145
14      0.019645  0.003158  0.008121  0.000061     0.019201  0.000125
15      0.052908  0.002131  0.007373  0.000004     0.017548  0.000059
16      0.051277  0.000737  0.007386  0.000004     0.017594  0.000048
17      0.045390  0.003071  0.008026  0.000038     0.019167  0.000103
18      0.046099  0.002215  0.008029  0.000040     0.019187  0.000107
19      0.035248  0.001172  0.008485  0.000022     0.019967  0.000052
20      0.036170  0.001185  0.008473  0.000020     0.019931  0.000056
21      0.038511  0.002096  0.007111  0.000039     0.017022  0.000136
22      0.037589  0.001494  0.007131  0.000050     0.017078  0.000151
23      0.030567  0.003466  0.007852  0.000038     0.018808  0.000073
24      0.030496  0.002215  0.007858  0.000032     0.018826  0.000069
25      0.022553  0.001915  0.008292  0.000012     0.019529  0.000048
26      0.021560  0.003937  0.008275  0.000019     0.019476  0.000061
27      0.041348  0.003625  0.007175  0.000010     0.017179  0.000051
28      0.037163  0.002694  0.007201  0.000019     0.017239  0.000063
29      0.034397  0.001625  0.007818  0.000026     0.018811  0.000085
30      0.031206  0.002215  0.007818  0.000025     0.018812  0.000087
31      0.023901  0.000684  0.008300  0.000055     0.019580  0.000117
32      0.023475  0.001092  0.008278  0.000051     0.019519  0.000115

   interval_score
             mean       std
0        0.064135  0.001033
1        0.063571  0.000931
2        0.066892  0.001551
3        0.066496  0.001703
4        0.070021  0.001493
5        0.069871  0.001556
6        0.064354  0.001264
7        0.064028  0.001400
8        0.065860  0.000969
9        0.065639  0.000468
10       0.071057  0.001318
11       0.070627  0.001151
12       0.059724  0.000811
13       0.062817  0.000436
14       0.068440  0.000545
15       0.068714  0.000465
16       0.068397  0.000045
17       0.068947  0.000659
18       0.068890  0.000476
19       0.074673  0.000894
20       0.074556  0.000789
21       0.067110  0.000551
22       0.066249  0.000986
23       0.067906  0.001060
24       0.067491  0.001268
25       0.072973  0.001234
26       0.072855  0.001140
27       0.068921  0.000312
28       0.068028  0.000840
29       0.067703  0.000497
30       0.067453  0.000188
31       0.073267  0.000494
32       0.073309  0.000564